### ISSUE TITLE
Traceback 

### ISSUE THREAD

**Issue by dodoaska** [Jumbo-WJB/Exchange_SSRF#2]
Traceback (most recent call last):
  File "/home/asus/Exchange_SSRF/exchange_ssrf_attacks.py", line 339, in <module>
    Brute_Account(args.target, email)
  File "/home/asus/Exchange_SSRF/exchange_ssrf_attacks.py", line 119, in Brute_Account
    for item in folderXML.findall(".//t:EmailAddress", exchangeNamespace):
NameError: name 'folderXML' is not defined

what i did wrong

**Comment by Jumbo-WJB** [comment]
do you use  python3.8+? and  `import xml.etree.cElementTree as ET` works in your python?

**Comment by dodoaska** [comment]
python3 -V    
Python 3.9.7

i dont know how to import
